### ISSUE TITLE
How to disable case sensitivity?

### ISSUE THREAD

**Issue by kings2u** [mohkale/consult-yasnippet#11] opened 2023-02-11 22:39 UTC
I noticed today that when narrowing candidates from `consult-yasnippet`,  matches are case-sensitive. So if I type "hash", I won’t get a yasnippet named "HASH". 

Could we have a user preference to turn of case-sensitive searching? Thanks!

**Comment by mohkale** [comment] 2023-02-11 22:59
@kings2u 

This isn't something that should be configured at this plugin. You should look into the completion facilities of your completion ui and emacs core. As a starter I'd recommend trying to set `completion-ignore-case` or `case-fold-search` and to confirm whether your completion ui (for example selectrum) maybe has support for configuring this.

Feel free to continue discussing or asking questions in this issue but I'm going to go ahead and close it.

**Closed by mohkale** 2023-02-11 22:59 UTC

**Comment by kings2u** [comment] 2023-02-11 23:49
> I'd recommend trying to set `completion-ignore-case` or `case-fold-search`

Oh darn, you’re right. Interestingly I already had both of these variables set to true. I use Orderless and Vertrico, and my problem was including `!ALIAS` in my search string in `consult-yasnippet` in order to exclude those snippets that had the term ALIAS in their name. Normally prefixing a word with `!` excludes just that word, but for some reason it excludes all yasnippets with any capital letter...

I’m still not sure why the usual method of Orderless filtering doesn’t work with `consult-yasnippet`, but I’m glad to have gotten closer to the problem. Thank you!

**Comment by mohkale** [comment] 2023-02-12 08:53
@kings2u 

What you've described is smart-case behaviour. By default just entering a term like "foo" will match case insensitively. For example "foo", "FOO", "FoO", etc. If you add a capital letter to the query then it will match case sensitively. Meaning "foO" only ever matches "foO". You mentioned you're using orderless so I suspect this is caused by `orderless-smart-case`.
